import matplotlib.pyplot as plt
import numpy as np
from datasets import altcoins_bought, btc_data

plt.style.use('seaborn')

# Altcoins
altcoins_table = altcoins_bought[['coin_name', 'buy', 'date']]
coins_by_buy_group = altcoins_table['buy'].value_counts()
x_labels = ['invest', 'unknown', 'no invest']

fig_1, ax_1 = plt.subplots()
rects1 = ax_1.bar(x_labels,
                  coins_by_buy_group.values)
ax_1.xaxis.set_major_locator(plt.MaxNLocator(integer=True))
ax_1.set_title('Number of coins in each group')
ax_1.bar_label(rects1, padding=3, size=12)

# Altcoins and random altcoins
altcoins_table_with_random = altcoins_bought[['coin_name', 'buy',
                                              'date', 'random_coin_name']]
altcoins_table_with_random.sort_values('date', inplace=True)
altcoins_table_with_random['date'] = altcoins_table_with_random['date'].dt.date

fig_tab_1, ax_tab_1 = plt.subplots(figsize=(4, 7))
ccolors = plt.cm.Blues(np.full(len(altcoins_table_with_random.iloc[0]), 0.2))
table = ax_tab_1.table(cellText=altcoins_table_with_random.to_numpy(),
                       colLabels=altcoins_table_with_random.columns.values,
                       colColours=ccolors,
                       loc='center')
ax_tab_1.axis('off')
table.scale(1.5, 1.5)
table.set_fontsize(15)

# Bitcoin
buy_dates = altcoins_table[altcoins_table['buy'] > 0]
buy_dates = buy_dates[['date']]
btc_prices_on_buy = buy_dates.merge(btc_data,
                                    left_on='date',
                                    right_on='date')

fig_2, ax_2 = plt.subplots()
ax_2.plot(btc_data['date'],
          btc_data['price'],
          zorder=1)
ax_2.scatter(btc_prices_on_buy['date'],
             btc_prices_on_buy['price'],
             s=30,
             c='r',
             zorder=2,
             label='Coin purchase')
ax_2.legend(loc='upper left')
ax_2.xaxis.set_major_locator(plt.MaxNLocator(7))
ax_2.tick_params(axis='x', labelrotation=45)
ax_2.set_title("Bitcoin's price history")

# Calculate profit for altcoins and bitcoin
invested_amount = 100
btc_price_sell = btc_data.query('date == date.max()')['price']
btc_price_sell = btc_price_sell.iloc[0]

altcoins_bought['%_profit'] = altcoins_bought['price_sell'] / altcoins_bought[
    'price_buy'] - 1
altcoins_bought['profit'] = invested_amount * altcoins_bought['%_profit']
altcoins_bought['%_random_coin_profit'] = altcoins_bought[
                                              'random_coin_price_sell'] \
                                          / altcoins_bought[
                                              'random_coin_price_buy'] - 1
altcoins_bought['random_coin_profit'] = invested_amount \
                                        * altcoins_bought[
                                            '%_random_coin_profit']
altcoins_bought['%_bitcoin_profit'] = btc_price_sell \
                                      / altcoins_bought['bitcoin_price_buy'] - 1
altcoins_bought['bitcoin_profit'] = invested_amount * \
                                    altcoins_bought['%_bitcoin_profit']

# For further analysis we get only coins from group 1 (unknown) and 2 (buy)
altcoins_1_2 = altcoins_bought[altcoins_bought['buy'] >= 1]

# Coins
altcoins_1_2.sort_values('profit', inplace=True)
fig_3, ax_3 = plt.subplots()
rects2 = ax_3.barh(altcoins_1_2['coin_name'],
                   round(altcoins_1_2['profit'], 2))
ax_3.set_title('Profit generated by altcoins')
ax_3.bar_label(rects2, padding=3)
ax_3.margins(x=0.08)

# Random coins
altcoins_1_2.sort_values('random_coin_profit', inplace=True)
fig_4, ax_4 = plt.subplots()
rects3 = ax_4.barh(altcoins_1_2['random_coin_name'],
                   round(altcoins_1_2['random_coin_profit'], 2))
ax_4.set_title('Profit generated by random altcoins')
ax_4.bar_label(rects3, padding=3)
ax_4.margins(x=0.08)

# Average profit
avg_profit_1_2 = altcoins_1_2['%_profit'].mean()
avg_profit_2 = altcoins_1_2[altcoins_1_2['buy'] == 2]['%_profit'].mean()
avg_random_coin_profit_1_2 = altcoins_1_2['%_random_coin_profit'].mean()
avg_random_coin_profit_2 = altcoins_1_2[altcoins_1_2['buy'] == 2][
    '%_random_coin_profit'].mean()
avg_bitcoin_profit_1_2 = altcoins_1_2['%_bitcoin_profit'].mean()
avg_bitcoin_profit_2 = altcoins_1_2[altcoins_1_2['buy'] == 2][
    '%_bitcoin_profit'].mean()

# Format values as percent
avg_profit_1_2 = round(avg_profit_1_2 * 100, 2)
avg_profit_2 = round(avg_profit_2 * 100, 2)
avg_random_coin_profit_1_2 = round(avg_random_coin_profit_1_2 * 100, 2)
avg_random_coin_profit_2 = round(avg_random_coin_profit_2 * 100, 2)
avg_bitcoin_profit_1_2 = round(avg_bitcoin_profit_1_2 * 100, 2)
avg_bitcoin_profit_2 = round(avg_bitcoin_profit_2 * 100, 2)

labels = ['unknown (1) & invest (2)', 'invest (2)']
coin_profit = [avg_profit_1_2, avg_profit_2]
random_coin_profit = [avg_random_coin_profit_1_2, avg_random_coin_profit_2]
bitcoin_profit = [avg_bitcoin_profit_1_2, avg_bitcoin_profit_2]

# Altcoins and random altcoins
x = np.arange(len(labels))
width = 0.35

fig_5, ax_5 = plt.subplots()
rects4 = ax_5.bar(x - width / 2, coin_profit, width, label='Altcoins')
rects5 = ax_5.bar(x + width / 2, random_coin_profit, width,
                  label='Random altcoins')
ax_5.set_ylabel('Profit (%)')
ax_5.set_xticks(x, labels)
ax_5.set_title(
    'Average percentage profit generated by one altcoin and random altcoin'
)
ax_5.legend(loc='upper left')
ax_5.bar_label(rects4, padding=3)
ax_5.bar_label(rects5, padding=3)

# Altcoins, random altcoins and bitcoin
width = 0.25

fig_6, ax_6 = plt.subplots()
rects6 = ax_6.bar(x, coin_profit, width, label='Altcoins')
rects7 = ax_6.bar(x + width, random_coin_profit, width, label='Random altcoins')
rects8 = ax_6.bar(x + width * 2, bitcoin_profit, width, label='Bitcoin')
ax_6.set_ylabel('Profit (%)')
ax_6.set_xticks(x + width, labels)
ax_6.set_title(
    'Average percentage profit generated by one altcoin, random altcoin and Bitcoin'
)
ax_6.legend(loc='upper left')
ax_6.bar_label(rects6, padding=3)
ax_6.bar_label(rects7, padding=3)
ax_6.bar_label(rects8, padding=3)

plt.show()

# Save charts and tables - uncomment if necessary
"""
dpi = 1000
directory = 'img/'

fig_tab_1.savefig(directory + 'altcoins_and_random_altcoins.png',
                  dpi=dpi,
                  bbox_inches='tight',
                  pad_inches=0)
fig_1.savefig(directory + 'number_of_coins_in_each_group.png', dpi=dpi)
fig_2.savefig(directory + 'bitcoin_price_history.png', dpi=dpi)
fig_3.savefig(directory + 'profit_generated_by_altcoins.png', dpi=dpi)
fig_4.savefig(directory + 'profit_generated_by_random_altcoins.png', dpi=dpi)
fig_5.savefig(directory + 'avg_percentage_profit_altcoin_random_altcoin.png',
              dpi=dpi)
fig_6.savefig(
    directory + 'avg_percentage_profit_altcoin_random_altcoin_bitcoin.png',
    dpi=dpi
)
"""
